/**
 * Code samples for the static pages, generated by the same `core/codegen` the
 * app's Code tab uses.
 *
 * Nothing on the site shows hand-written builder code. A sample that was typed
 * into a guide drifts the first time a library renames a method; a sample that
 * is generated at build time can only say what the export says, and the export
 * is round-tripped against the published libraries by
 * `scripts/verify-codegen.ts`.
 */

import { attachEditorFields } from "@/core/serialization/normalize";
import { generateCode, type CodeTarget } from "@/core/codegen";
import type { WebhookMessage } from "@/core/schema/types";

/**
 * The reference card: one accent-striped container with a heading, a divider
 * and a link button. It is the same message as the minimal JSON payload in the
 * Components V2 guide, so a reader can hold the three forms side by side.
 */
export const REFERENCE_CARD: WebhookMessage = attachEditorFields({
  components: [
    {
      type: 17,
      accent_color: 0x5865f2,
      components: [
        { type: 10, content: "# Server update\nEverything you need in one place." },
        { type: 14, divider: true, spacing: 1 },
        {
          type: 1,
          components: [
            { type: 2, style: 5, label: "Read the guide", url: "https://example.com/update" },
          ],
        },
      ],
    },
  ],
});

/**
 * A section with a thumbnail beside its text — the layout a legacy embed could
 * not express and the one people most often ask how to build in code.
 */
export const SECTION_CARD: WebhookMessage = attachEditorFields({
  components: [
    {
      type: 17,
      accent_color: 0x57f287,
      components: [
        {
          type: 9,
          components: [
            { type: 10, content: "## Friday game night" },
            { type: 10, content: "Doors open at 8 PM. Bring a friend and a headset." },
          ],
          accessory: {
            type: 11,
            media: { url: "https://example.com/game-night.png" },
            description: "Game night artwork",
          },
        },
        {
          type: 1,
          components: [
            { type: 2, style: 3, label: "I'm in", custom_id: "rsvp:yes" },
            { type: 2, style: 2, label: "Maybe", custom_id: "rsvp:maybe" },
          ],
        },
      ],
    },
  ],
});

export function sample(message: WebhookMessage, target: CodeTarget): string {
  return generateCode(message, target).trimEnd();
}
