/**
 * Discord Components V2 schema.
 *
 * Types here mirror the wire format Discord expects when posting to a webhook
 * with the `IS_COMPONENTS_V2` message flag (1 << 15) set. They are intentionally
 * close to the official API shape so that `serialization/encode.ts` can emit a
 * payload Discord accepts with minimal transformation.
 *
 * Editor-only fields (an `_id` we generate for selection/diffing) are stripped
 * before export — see `serialization/normalize.ts`. Discord's own optional
 * per-component `id` integer (a separate field used for stable identity across
 * edits) is preserved as `componentId` and round-trips untouched.
 *
 * Reference: https://docs.discord.com/developers/components/reference
 */

/** Discord component type discriminator. */
export const ComponentType = {
  ActionRow: 1,
  Button: 2,
  StringSelect: 3,
  TextInput: 4,
  UserSelect: 5,
  RoleSelect: 6,
  MentionableSelect: 7,
  ChannelSelect: 8,
  Section: 9,
  TextDisplay: 10,
  Thumbnail: 11,
  MediaGallery: 12,
  File: 13,
  Separator: 14,
  Container: 17,
} as const;

export type ComponentTypeValue = (typeof ComponentType)[keyof typeof ComponentType];

/** Discord button style discriminator. */
export const ButtonStyle = {
  Primary: 1,
  Secondary: 2,
  Success: 3,
  Danger: 4,
  Link: 5,
  Premium: 6,
} as const;

export type ButtonStyleValue = (typeof ButtonStyle)[keyof typeof ButtonStyle];

/** Separator vertical spacing. */
export const SeparatorSpacing = {
  Small: 1,
  Large: 2,
} as const;

export type SeparatorSpacingValue = (typeof SeparatorSpacing)[keyof typeof SeparatorSpacing];

/**
 * Discord channel types accepted as `channel_types` filters on a Channel Select.
 * Numeric values mirror the API; the editor only surfaces the common ones in
 * the picker but accepts any integer for round-trip safety on import.
 */
export const ChannelType = {
  GuildText: 0,
  DM: 1,
  GuildVoice: 2,
  GroupDM: 3,
  GuildCategory: 4,
  GuildAnnouncement: 5,
  AnnouncementThread: 10,
  PublicThread: 11,
  PrivateThread: 12,
  GuildStageVoice: 13,
  GuildDirectory: 14,
  GuildForum: 15,
  GuildMedia: 16,
} as const;

export type ChannelTypeValue = (typeof ChannelType)[keyof typeof ChannelType];

/**
 * Editor-only identifier attached to every component so the builder can track
 * selection and reorder without relying on array indices. Stripped at export.
 */
export type EditorId = string;

/** Common fields present on every editor component. */
export interface BaseComponent {
  /** Editor-only stable id. Not sent to Discord. */
  _id: EditorId;
  /**
   * Discord's optional per-component 32-bit identifier. Auto-generated by
   * Discord when omitted; preserved verbatim on import/restore so callers
   * referencing components by id keep working.
   */
  id?: number;
  type: ComponentTypeValue;
}

/** Partial emoji used on buttons / select options. */
export interface PartialEmoji {
  id?: string | null;
  name?: string | null;
  animated?: boolean;
}

/**
 * Unfurled media item used by thumbnails, galleries, and files.
 *
 * Discord accepts either an absolute `url` (https:// or `attachment://<filename>`)
 * or an `attachment_id` snowflake referring to an already-uploaded attachment.
 * Restored messages also include resolved fields (`proxy_url`, `height`,
 * `width`, `content_type`, `loading_state`) which we preserve untouched but
 * do not render or edit directly.
 */
export interface UnfurledMediaItem {
  url?: string;
  attachment_id?: string;
  proxy_url?: string;
  height?: number | null;
  width?: number | null;
  content_type?: string;
  loading_state?: number;
}

// ────────────────────────────────────────────────────────────────────────────
// Leaf components
// ────────────────────────────────────────────────────────────────────────────

export interface TextDisplayComponent extends BaseComponent {
  type: typeof ComponentType.TextDisplay;
  content: string;
}

export interface ThumbnailComponent extends BaseComponent {
  type: typeof ComponentType.Thumbnail;
  media: UnfurledMediaItem;
  description?: string;
  spoiler?: boolean;
}

export interface MediaGalleryItem {
  media: UnfurledMediaItem;
  description?: string;
  spoiler?: boolean;
}

export interface MediaGalleryComponent extends BaseComponent {
  type: typeof ComponentType.MediaGallery;
  items: MediaGalleryItem[];
}

/**
 * Unlike Thumbnail / MediaGallery, a File's media only renders an *uploaded*
 * attachment — its `url` must use the `attachment://<filename>` form (or carry
 * an `attachment_id`). Discord rejects an external https URL here. Validation
 * enforces this; the editor's in-session `session://` refs rewrite to
 * `attachment://` at send time.
 */
export interface FileComponent extends BaseComponent {
  type: typeof ComponentType.File;
  file: UnfurledMediaItem;
  spoiler?: boolean;
}

export interface SeparatorComponent extends BaseComponent {
  type: typeof ComponentType.Separator;
  divider?: boolean;
  spacing?: SeparatorSpacingValue;
}

/**
 * Buttons split into two structural variants:
 *  - URL/Premium buttons carry a target (`url` or `sku_id`) and never a custom_id.
 *  - Interactive buttons carry a `custom_id` and a non-link style.
 *
 * Webhook messages can include interactive buttons, but interactions cannot be
 * handled without a backend. We still allow editing them so users can ship
 * messages a separate bot will receive.
 */
export interface LinkButtonComponent extends BaseComponent {
  type: typeof ComponentType.Button;
  style: typeof ButtonStyle.Link;
  label?: string;
  emoji?: PartialEmoji;
  url: string;
  disabled?: boolean;
}

export interface PremiumButtonComponent extends BaseComponent {
  type: typeof ComponentType.Button;
  style: typeof ButtonStyle.Premium;
  sku_id: string;
  disabled?: boolean;
}

export interface InteractiveButtonComponent extends BaseComponent {
  type: typeof ComponentType.Button;
  style:
    | typeof ButtonStyle.Primary
    | typeof ButtonStyle.Secondary
    | typeof ButtonStyle.Success
    | typeof ButtonStyle.Danger;
  label?: string;
  emoji?: PartialEmoji;
  custom_id: string;
  disabled?: boolean;
}

export type ButtonComponent =
  | LinkButtonComponent
  | PremiumButtonComponent
  | InteractiveButtonComponent;

// ────────────────────────────────────────────────────────────────────────────
// Select components (types 3, 5, 6, 7, 8)
//
// All five are interactive — Discord delivers their values via an interaction
// payload which only a bot can receive. The editor still exposes them so
// users can lay out a message that a bot they own will later process.
// ────────────────────────────────────────────────────────────────────────────

/** Option entry on a StringSelect. */
export interface StringSelectOption {
  label: string;
  value: string;
  description?: string;
  emoji?: PartialEmoji;
  default?: boolean;
}

interface BaseSelectComponent extends BaseComponent {
  custom_id: string;
  placeholder?: string;
  min_values?: number;
  max_values?: number;
  disabled?: boolean;
}

export interface StringSelectComponent extends BaseSelectComponent {
  type: typeof ComponentType.StringSelect;
  options: StringSelectOption[];
}

/** Default-value entries for the snowflake-resolving selects. */
export interface DefaultValueUser {
  id: string;
  type: "user";
}
export interface DefaultValueRole {
  id: string;
  type: "role";
}
export interface DefaultValueChannel {
  id: string;
  type: "channel";
}

export interface UserSelectComponent extends BaseSelectComponent {
  type: typeof ComponentType.UserSelect;
  default_values?: DefaultValueUser[];
}

export interface RoleSelectComponent extends BaseSelectComponent {
  type: typeof ComponentType.RoleSelect;
  default_values?: DefaultValueRole[];
}

export interface MentionableSelectComponent extends BaseSelectComponent {
  type: typeof ComponentType.MentionableSelect;
  default_values?: Array<DefaultValueUser | DefaultValueRole>;
}

export interface ChannelSelectComponent extends BaseSelectComponent {
  type: typeof ComponentType.ChannelSelect;
  channel_types?: number[];
  default_values?: DefaultValueChannel[];
}

export type SelectComponent =
  | StringSelectComponent
  | UserSelectComponent
  | RoleSelectComponent
  | MentionableSelectComponent
  | ChannelSelectComponent;

// ────────────────────────────────────────────────────────────────────────────
// Layout components
// ────────────────────────────────────────────────────────────────────────────

/** A Section accessory is either a single Button or a Thumbnail. */
export type SectionAccessory = ButtonComponent | ThumbnailComponent;

export interface SectionComponent extends BaseComponent {
  type: typeof ComponentType.Section;
  /** 1–3 TextDisplay children. */
  components: TextDisplayComponent[];
  accessory: SectionAccessory;
}

/**
 * Action rows hold EITHER up to 5 buttons OR exactly one select component.
 * The two shapes never mix — Discord rejects the row otherwise. We model both
 * variants in a single component so the editor can swap content without
 * recreating the row.
 */
export interface ActionRowComponent extends BaseComponent {
  type: typeof ComponentType.ActionRow;
  components: ButtonComponent[] | [SelectComponent];
}

/**
 * Top-level container. Renders with a left accent stripe in Discord, similar
 * to the legacy embed look. Cannot nest another Container.
 */
export interface ContainerComponent extends BaseComponent {
  type: typeof ComponentType.Container;
  /**
   * RGB integer (0xRRGGBB) or null. Discord renders no accent stripe when null.
   * We keep `undefined` and `null` distinct so the wire payload only emits the
   * field when the user explicitly chose a color.
   */
  accent_color?: number | null;
  spoiler?: boolean;
  components: ContainerChild[];
}

/** Components allowed inside a Container (no nested Container). */
export type ContainerChild =
  | ActionRowComponent
  | TextDisplayComponent
  | SectionComponent
  | MediaGalleryComponent
  | SeparatorComponent
  | FileComponent;

/** Top-level components allowed on a Components V2 message. */
export type TopLevelComponent =
  | ActionRowComponent
  | SectionComponent
  | TextDisplayComponent
  | MediaGalleryComponent
  | SeparatorComponent
  | FileComponent
  | ContainerComponent;

/** Any component (used for tree traversal). */
export type AnyComponent =
  | TopLevelComponent
  | ContainerChild
  | ButtonComponent
  | ThumbnailComponent
  | SectionAccessory
  | SelectComponent;

// ────────────────────────────────────────────────────────────────────────────
// Message-level options
// ────────────────────────────────────────────────────────────────────────────

/**
 * `allowed_mentions` controls which mentions in TextDisplay content resolve
 * to real pings. Without it, an `@everyone` token in a TextDisplay pings the
 * channel. Each `parse` entry whitelists a class of mention; the explicit
 * `roles`/`users` arrays whitelist specific snowflakes.
 *
 * Discord rejects a payload that supplies BOTH `parse: ["roles"]` and a
 * `roles: [...]` array (mutually exclusive); the same rule applies to users.
 */
export type AllowedMentionType = "roles" | "users" | "everyone";

export interface AllowedMentions {
  parse?: AllowedMentionType[];
  roles?: string[];
  users?: string[];
  /** Whether the author of the referenced message gets pinged on a reply. */
  replied_user?: boolean;
}

/**
 * Forge a reply by pointing at another message. For webhook execute Discord
 * accepts `message_id` (required) plus optional `channel_id` and
 * `fail_if_not_exists`. `type` defaults to 0 (default reply).
 */
export interface MessageReference {
  message_id: string;
  channel_id?: string;
  guild_id?: string;
  type?: number;
  fail_if_not_exists?: boolean;
}

/**
 * Message-level metadata. With Components V2, `content` and `embeds` are
 * forbidden — only `components` ship to Discord. Webhook execution params
 * (username, avatar_url, allowed_mentions, message_reference, thread_name,
 * applied_tags, suppress_notifications) live alongside for the executor to
 * consume.
 *
 * `flags` is computed at send time — IS_COMPONENTS_V2 is always present, and
 * `suppress_notifications` (1 << 12) is OR-ed in when the user enables it.
 */
export interface WebhookMessage {
  /** Override webhook display name. */
  username?: string;
  /** Override webhook avatar URL. */
  avatar_url?: string;
  /** Whether to read message content with TTS. */
  tts?: boolean;
  /** Send silently — recipients see the message but get no notification. */
  suppress_notifications?: boolean;
  /** Mention-resolution policy. See `AllowedMentions`. */
  allowed_mentions?: AllowedMentions;
  /** Reply to another message (forum/channel reply target). */
  message_reference?: MessageReference;
  /**
   * Name of the thread to create when posting into a forum/media channel.
   * Required for forum-channel posts; ignored elsewhere.
   */
  thread_name?: string;
  /**
   * Forum tags to apply to the new thread. Only honoured when posting to a
   * forum channel with `thread_name` set.
   */
  applied_tags?: string[];
  /** Top-level component list. Order matters — this is the render order. */
  components: TopLevelComponent[];
}

/**
 * Message flag that tells Discord this message uses the Components V2 layout
 * system. Must be set when posting; the editor always emits it.
 */
export const MESSAGE_FLAG_IS_COMPONENTS_V2 = 1 << 15;

/**
 * Silent-send flag. When set, recipients see the message but receive no
 * notification (mobile push, desktop toast, mention badge).
 */
export const MESSAGE_FLAG_SUPPRESS_NOTIFICATIONS = 1 << 12;

/**
 * Compute the `flags` integer Discord expects on the wire. `IS_COMPONENTS_V2`
 * is always present — every message this app emits is V2, and Discord rejects
 * V2 components when the flag is absent — with `SUPPRESS_NOTIFICATIONS` OR-ed
 * in when the user enabled silent send. This is the single source of truth for
 * flags across send, JSON export, and share-link serialization.
 */
export function computeMessageFlags(message: WebhookMessage): number {
  let flags = MESSAGE_FLAG_IS_COMPONENTS_V2;
  if (message.suppress_notifications) flags |= MESSAGE_FLAG_SUPPRESS_NOTIFICATIONS;
  return flags;
}

/** Inverse of {@link computeMessageFlags}: read the silent-send bit back. */
export function flagsHaveSuppressNotifications(flags: unknown): boolean {
  const n = Number(flags);
  return Number.isFinite(n) && (n & MESSAGE_FLAG_SUPPRESS_NOTIFICATIONS) !== 0;
}
